### ISSUE TITLE
counterIntervalSimulator number of signals overrides total number of signals

### ISSUE THREAD

**Issue by jennyknuth** [nio-blocks/simulator#39]
It would be more intuitive for total number of signals to be the dominant default, rather than number of signals. 

The current behavior keeps counting until the next multiple of the number of signals is reached and does not necessarily stop counting at total number of signals.

**Comment by mattdodge** [comment]
@jennyknuth Next time please include the example of what happened or an example that can reproduce.

With a configuration like the following:
 * Total Number of Signals: 5
 * Number of Signals (signals per notification: 2

We would see the following notifications
 * [1, 2]
 * [3, 4]
 * [5, 6]

So, 6 signals, instead of 5. The proposed fix would make it look like this instead:
 * [1, 2]
 * [3, 4]
 * [5]

The argument would be that if you wanted it to actually notify 6 signals you should just change your total number of signals to 6, there is no way in the current setup to achieve the desired output.

**Comment by mattdodge** [comment]
@kevincrabbe this is a good one to start with

**Comment by kevincrabbe** [comment]
Pull Request got merged: https://github.com/nio-blocks/simulator/pull/41
